sudo: false

language: node_js

node_js:
  - 6.10.3

install:
  - npm install

script:
  - npm test
  - npm run dist
  - npm run build

deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
