/** Declaration file generated by dts-gen */

declare module 'jsdom' {

  export declare class JSDOM extends Document {
    public window: Window;
    constructor (markup?: string, config?: any);
  }

}
