#!/usr/bin/env bash

set -e

rm -rf docs/build/

bluekit --baseDir src/ts/ --paths . --exclude "./componentsIndex.js"

mkdir -p docs/build/js/

browserify -d docs/src/ts/index.tsx -p [tsify -p docs/src/ts/tsconfig.json] -t brfs -t envify | exorcist docs/build/js/index.js.map > docs/build/js/index.js
