#!/usr/bin/env bash

set -e

mkdir -p docs/build/js/
mkdir -p docs/build/css/

concurrently --kill-others \
  --prefix='name' \
  --names='watch-less ,watch-js   ,livereload ,http-server' \
  --prefix-colors='cyan,red,magenta,green' \
  'watch-less-do-more -u autoprefixer -i docs/src/less/index.less -o docs/build/css/index.css' \
  'LIVERELOAD=true watchify -d docs/src/ts/index.tsx -p [tsify] -t brfs -t envify -o docs/build/js/index.js -v' \
  'livereload docs/build/css/' \
  'http-server -c-0 docs/ -o'
